apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcs-deploy
  labels:
    app: bcs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bcs
  template:
    metadata:
      labels:
        app: bcs
    spec:
      containers:
        - name: bcs
          image: crpi-38ox03csjf2n9jik.cn-wulanchabu.personal.cr.aliyuncs.com/perfectdocker/bcs:latest
          ports:
            - containerPort: 9090
